### PR TITLE
Update for SMAPI 3.0, internal refactoring, various fixes

### PR DESCRIPTION
**Pull request by Pathoschild**
This pull request...

* Updates the code for SMAPI 3.0.
* Updates the mod build package.
* Migrates to the new simplified `.csproj` format.
* Fixes multiplayer support by scanning locations instead of using `Utility.findHorse`. This will also use the first unused horse (which will usually work better in multiplayer), instead of trying to get their owned horse.
* Fixes an issue where a player riding a horse can summon a second one.
* Fixes compatibility with recent versions of Tractor Mod.

Let me know if you want me to change anything!

### CODE REVIEW

**Comment by Sanaki** [comment]
Pulled and built this in MonoDevelop on Linux, the whistle sound doesn't happen for me (yes, it's enabled in the config), and my girlfriend on Windows gets the following error on startup from that same build (and can't use it):

```[Horse Whistle] Mod crashed on entry and might not work correctly. Technical details:
System.MissingFieldException: Field not found: 'StardewValley.Game1.audioEngine'.
   at HorseWhistle.ModEntry.Entry(IModHelper helper)
   at StardewModdingAPI.Framework.SCore.LoadMods(IModMetadata[] mods, JsonHelper jsonHelper, ContentCoordinator contentCore, ModDatabase modDatabase) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SCore.cs:line 824
```

The whistle sound didn't work for me in the official build either, but that build supposedly didn't trigger the error on Windows.

**Comment by Pathoschild** [comment]
@Sanaki The sound not playing on Linux/Mac is a known limitation in the mod. The error she got isn't normal though; can you have her try it again, [upload her SMAPI log](https://log.smapi.io) (see instructions on that page), and post a link here?

You don't really need to compile it yourself though. The [official version](https://www.nexusmods.com/stardewvalley/mods/1131) is compatible with the latest versions of SMAPI and Stardew Valley, and we'll post an unofficial update to [mods.smapi.io](https://mods.smapi.io/) if needed when SMAPI 3.0 is released.

**Comment by Sanaki** [comment]
@Pathoschild Pretty sparse, she just opened the game and closed it, but the mod won't run after that point anyway: https://log.smapi.io/2wPMiELT
My assumption is that the error may be due to me compiling on linux for a windows system, but this is the only mod that seemed to have issues from that, which I found... odd. Perhaps a result of whatever causes the sound to fail on POSIX systems? Either way, I'm happy to provide any other info if you need it.

**Comment by Pathoschild** [comment]
@Sanaki Not sure what's causing that issue in your build, but I posted [an unofficial update](https://community.playstarbound.com/threads/updating-mods-for-stardew-valley-1-3.142524/page-82#post-3348278) that should work on both Linux and Windows.

**Pull request merged**
